# Generated by Django 5.1.15 on 2026-05-23 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=300)),
                ('url', models.TextField()),
                ('url_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('source', models.CharField(choices=[('indeed', 'Indeed'), ('linkedin', 'LinkedIn'), ('japan_dev', 'Japan Dev'), ('tokyo_dev', 'Tokyo Dev'), ('daijob', 'Daijob'), ('custom', 'Custom/Other')], default='custom', max_length=50)),
                ('salary', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('full_description', models.TextField(blank=True, default='')),
                ('tech_stack', models.JSONField(blank=True, null=True)),
                ('language', models.CharField(blank=True, choices=[('EN', 'English'), ('JP', 'Japanese')], max_length=5, null=True)),
                ('experience_required', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['source'], name='jobs_job_source_e2155e_idx'), models.Index(fields=['company'], name='jobs_job_company_73ae7f_idx'), models.Index(fields=['is_active'], name='jobs_job_is_acti_b6ae73_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(max_length=100)),
                ('profile_title', models.CharField(blank=True, default='', max_length=200)),
                ('match_tier', models.CharField(choices=[('S', 'S Tier'), ('A', 'A Tier'), ('B', 'B Tier'), ('C', 'C Tier'), ('F', 'F Tier')], max_length=2)),
                ('rank', models.PositiveIntegerField()),
                ('jd_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='jobs.job')),
            ],
            options={
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['profile_id'], name='jobs_jobran_profile_b8b94b_idx'), models.Index(fields=['match_tier'], name='jobs_jobran_match_t_2d3e93_idx')],
                'unique_together': {('job', 'profile_id')},
            },
        ),
    ]
