# Generated by Django 5.1.15 on 2026-05-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_formatted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_formatted'], name='jobs_job_is_form_2ea8f7_idx'),
        ),
    ]
