# Generated by Django 5.1.15 on 2026-05-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_is_formatted_job_jobs_job_is_form_2ea8f7_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
