# Generated by Django 5.1.15 on 2026-05-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_add_raw_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='alert_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
