# Generated by Django 5.1.15 on 2026-05-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_alert_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='language',
            field=models.CharField(blank=True, choices=[('EN', 'English'), ('JP', 'Japanese'), ('non-english', 'Non-English')], max_length=20, null=True),
        ),
    ]
