# Generated by Django 5.1.15 on 2026-05-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_ranked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_ranked'], name='jobs_job_is_rank_cac937_idx'),
        ),
    ]
