# Generated by Django 5.1.15 on 2026-06-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_job_country_job_is_remote_job_location_job_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_applied',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
