# Generated by Django 5.1.15 on 2026-06-21 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_job_is_applied'),
        ('jobs', '0010_update_source_choices'),
    ]

    operations = [
    ]
