# Generated by Django 5.1.15 on 2026-06-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_merge_0009_job_is_applied_0010_update_source_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='scraped_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
